### ISSUE TITLE
I would need the executable

### ISSUE THREAD

**Issue by rubenbitrian** [mpapierski/from-hdd-lg-to-pc#1]
Hello,
I would need if possible, that you upload the compiled program since I need to use it but I do not have the necessary tools to make it work.
I await your reply. Thank you very much for your attention.
Translated with google translator, I do not handle English well.

**Comment by mpapierski** [comment]
Hi,

I recevied this source code from original author. Right now I dont have necessary tools to fulfill your request, though it is worth to ask original author about the executables. I definetely look forward to maintain this project. See readme.

> The author: Val238
> e-mail: val238@mail.ru

Thanks for your interest :)

**Comment by mpapierski** [comment]
I'm also looking for any contributors!

**Comment by mpapierski** [comment]
I've set up appveyor project for building this with few small changes on VS, though I think the source code relies too much on Borland C++ to make use of this.
I think we're getting somewhere in compiling this on VS:

https://ci.appveyor.com/project/mpapierski/from-hdd-lg-to-pc/build/job/bywrkmfff3n0pv4w

Many errors though now.

**Comment by mpapierski** [comment]
Hi @cybernegocios 

Can you try this build?

https://ci.appveyor.com/project/mpapierski/from-hdd-lg-to-pc/build/job/r2815s4tcoutpiie/artifacts

I made some progress with porting this source code from BCB to VS and also I've set up a appveyor CI. This exe would require VS2015 redist package. Please let me know if you can use this software.

**Comment by mpapierski** [comment]
@cybernegocios I've set up also deployment to GitHub releases: https://github.com/mpapierski/from-hdd-lg-to-pc/releases/download/1.0.0/from_hdd_lg_to_pc.exe

Hope it works for you!
